[[redirects]]
  from = "/auth/*"
  to = "https://excelanalytics-backend-l7ql.onrender.com/auth/:splat"
  status = 200
  force = true
  headers = { 
    Access-Control-Allow-Origin = "https://visualexcel.netlify.app", 
    Access-Control-Allow-Credentials = "true", 
    Set-Cookie = "*" 
  }
